### ISSUE TITLE
Log Behavior 

### ISSUE THREAD

**Issue by gocanto** [laravel/internals#29]
Apologize if this is a bug, if it does, I will delete right away. 

My Idea is to control the errors before the `Log` object is bind to the main container. For example: If there's an error in `config/app.php` the application will say something like: 

```
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class log does not exist' in /Users/freek/dev/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:776
Stack trace:
#0 /Users/freek/dev/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(776): ReflectionClass->__construct('log')
#1 /Users/freek/dev/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(656): Illuminate\Container\Container->build('log', Array)
#2 /Users/freek/dev/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(644): Illuminate\Container\Container->make('log', Array)
#3 /Users/freek/dev/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(887): Illuminate\Foundation\Application->make('Psr\\Log\\LoggerI...')
```

Instead says where the error was. I am not pretty sure where to star this issue approach, but as I said, you guys can point me on the right direction.

**Comment by gocanto** [comment]
In fact, there is a conversation related to this on https://github.com/laravel/framework/issues/11724 where  @GrahamCampbell talked about capture the exception on line and see what the error was about and after two hours I came with the issue was an ```,``` out off place in the file mentioned above.
