### ISSUE TITLE
Debug in Laravel

### ISSUE THREAD

**Issue by uonick** [laravel/internals#959]
Current debug system in Laravel like...

![screen shot 2018-01-16 at 17 59 50](https://user-images.githubusercontent.com/365029/34990381-ba0b990c-fae7-11e7-815b-272d751027e1.png)

1. Table name?
2. Too many lines to read
3. Too many of unnecessary information

![giphy](https://user-images.githubusercontent.com/365029/34990551-52c47966-fae8-11e7-85c5-ce3bcd6d7a38.gif)

**Comment by michaeldyrynda** [comment]
![](https://media3.giphy.com/media/3oFzmdeDktiER4vDrO/giphy.gif)

**Comment by sisve** [comment]
Doesn't the exception message show the sql statement? What you're highlighting is the arguments in the stack trace.

**Comment by uonick** [comment]
@sisve **That is the problem**. There is a **lot of information**, but it **does not help**. 

91 lines of stupid debug trace:

```
[2018-01-16 12:59:30] testing.ERROR: PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1244-19' for key 'PRIMARY' in /vagrant/www/fitster/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105
Stack trace:
#0 /vagrant/www/fitster/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(105): PDOStatement->execute(NULL)
#1 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Database/Connection.php(449): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Database/Connection.php(640): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into `fi...', Array)
#3 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('insert into `fi...', Array, Object(Closure))
#4 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Database/Connection.php(450): Illuminate\Database\Connection->run('insert into `fi...', Array, Object(Closure))
#5 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Database/Connection.php(404): Illuminate\Database\Connection->statement('insert into `fi...', Array)
#6 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert into `fi...', Array)
#7 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2133): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `fi...', Array, 'id')
#8 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1251): Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#9 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(688): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#10 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(653): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(522): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#12 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php(284): Illuminate\Database\Eloquent\Model->save()
#13 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Support/helpers.php(964): Illuminate\Database\Eloquent\Relations\HasOneOrMany->Illuminate\Database\Eloquent\Relations\{closure}(Object(App\Models\ServiceMedia))
#14 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php(285): tap(Object(App\Models\ServiceMedia), Object(Closure))
#15 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php(299): Illuminate\Database\Eloquent\Relations\HasOneOrMany->create(Array)
#16 /vagrant/www/fitster/app/Models/Service.php(135): Illuminate\Database\Eloquent\Relations\HasOneOrMany->createMany(Array)
#17 /vagrant/www/fitster/app/Models/Service.php(57): App\Models\Service->attachImages(Array)
#18 /vagrant/www/fitster/app/Http/Controllers/Coach/ServicesController.php(135): App\Models\Service->createFrom(Object(App\Http\Requests\CoachServiceRequest))
#19 [internal function]: App\Http\Controllers\Coach\ServicesController->store(Object(App\Http\Requests\CoachServiceRequest), 'ru', 'jefimov380418')
#20 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#21 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('store', Array)
#22 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Coach\ServicesController), 'store')
#23 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#24 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Routing/Router.php(572): Illuminate\Routing\Route->run()
#25 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /vagrant/www/fitster/app/Http/Middleware/SetUserLastVisitTime.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\SetUserLastVisitTime->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /vagrant/www/fitster/app/Http/Middleware/Restricted.php(21): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\Restricted->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /vagrant/www/fitster/app/Http/Middleware/StoreGeoIPData.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\StoreGeoIPData->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /vagrant/www/fitster/app/Http/Middleware/Locale.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\Locale->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Routing/Router.php(574): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#61 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Routing/Router.php(533): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#62 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Routing/Router.php(511): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#63 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#64 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#65 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#66 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#69 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#70 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#71 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(234): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#72 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(206): Illuminate\Foundation\Testing\TestCase->call('POST', 'http://fitster....', Array, Array, Array, Array, '{"service":{"na...')
#73 /vagrant/www/fitster/tests/Feature/ServiceFeatureTest.php(355): Illuminate\Foundation\Testing\TestCase->json('POST', 'http://fitster....', Array)
#74 /vagrant/www/fitster/tests/Feature/ServiceFeatureTest.php(337): Tests\Http\ServiceFeatureTest->tryToCreateServiceWithOffersViaHttpRequest(Object(App\Models\User), Array)
#75 /vagrant/www/fitster/vendor/laravel/framework/src/Illuminate/Support/Collection.php(287): Tests\Http\ServiceFeatureTest->Tests\Http\{closure}(Array, 7)
#76 /vagrant/www/fitster/tests/Feature/ServiceFeatureTest.php(338): Illuminate\Support\Collection->each(Object(Closure))
#77 [internal function]: Tests\Http\ServiceFeatureTest->testCreateCoachServiceWithOffers()
#78 /vagrant/www/fitster/vendor/phpunit/phpunit/src/Framework/TestCase.php(1054): ReflectionMethod->invokeArgs(Object(Tests\Http\ServiceFeatureTest), Array)
#79 /vagrant/www/fitster/vendor/phpunit/phpunit/src/Framework/TestCase.php(905): PHPUnit_Framework_TestCase->runTest()
#80 /vagrant/www/fitster/vendor/phpunit/phpunit/src/Framework/TestResult.php(686): PHPUnit_Framework_TestCase->runBare()
#81 /vagrant/www/fitster/vendor/phpunit/phpunit/src/Framework/TestCase.php(860): PHPUnit_Framework_TestResult->run(Object(Tests\Http\ServiceFeatureTest))
#82 /vagrant/www/fitster/vendor/phpunit/phpunit/src/Framework/TestSuite.php(722): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#83 /vagrant/www/fitster/vendor/phpunit/phpunit/src/Framework/TestSuite.php(722): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#84 /vagrant/www/fitster/vendor/phpunit/phpunit/src/Framework/TestSuite.php(722): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#85 /vagrant/www/fitster/vendor/phpunit/phpunit/src/Extensions/RepeatedTest.php(83): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#86 /vagrant/www/fitster/vendor/phpunit/phpunit/src/Framework/TestSuite.php(722): PHPUnit_Extensions_RepeatedTest->run(Object(PHPUnit_Framework_TestResult))
#87 /vagrant/www/fitster/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(517): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#88 /vagrant/www/fitster/vendor/phpunit/phpunit/src/TextUI/Command.php(186): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array, true)
#89 /vagrant/www/fitster/vendor/phpunit/phpunit/src/TextUI/Command.php(116): PHPUnit_TextUI_Command->run(Array, true)
#90 /vagrant/www/fitster/vendor/phpunit/phpunit/phpunit(52): PHPUnit_TextUI_Command::main()
#91 {main}
```

**Comment by uonick** [comment]
Default PHP errors are **more informative** than this

**Comment by 36864** [comment]
The very first line of that stack trace tells you the exact problem.
The rest of the stack trace has some key points that tell you the exact line on each file involved in the error. 
Going purely off the trace, it looks like line 355 of your ServiceFeatureTest class is attempting to create a new model with a duplicate primary key. This data being passed into the tryToCreateServiceWithOffersViaHttpRequest method is being build somewhere in the testCreateCoachServiceWithOffers.

What more would you like a stack trace to show you?

**Comment by uonick** [comment]
@36864 
1. Table name
2. Bind params (from prepared statements)
3. Class name with error
4. Line of code in file

All the rest is **unnecessary** (except 3-5 class names in trace)

(p.s: I found in what the error, not the first year I write on laravel, but today...)

**Comment by sisve** [comment]
The message does not contain any table name because mysql doesn't tell us which table caused the problem. Only the name of the key with conflicts, which was the slightly ambiguous `PRIMARY` key. Who would show you the table name? What about sql statements that touches several tables? I guess you could argue that `Builder::insertGetId(...)` would catch exceptions and rethrow an exception with the _base_ table, the one it originally operates on, but there's no guarantee that the error is actually with that table. And if we tell you the wrong table, wouldn't that be worse?

I need the entire stack trace to help people debug their problems. I can use it to read which middlewares are used (and when people forgotten to execute the StartSession). So your claim that the entire stack trace in unnecessary is based on your specific use-case.

Most of the things you ask about makes sense from an interactive ui perspective; but what you ask for would create even more text output in a console.

**Comment by uonick** [comment]
@sisve I partially agree. But some core traces is unnecessary. 5-10 lines of code is normal.

**Comment by 36864** [comment]
5-10 lines wouldn't even reach your application's code in this case, and in many similar cases when the error is thrown by a framework method. How would that be of any help?

**Comment by uonick** [comment]
U don't need the code of the framework. Only application trace. For example:

```
[2018-01-16 14:52:40] testing.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to App\Models\Service::getPreparedArray() must be of the type array, null given, called in /vagrant/www/fitster/app/Models/Service.php on line 53 in /vagrant/www/fitster/app/Models/Service.php:144
Stack trace:
#0 /vagrant/www/fitster/app/Models/Service.php(53): App\Models\Service->getPreparedArray(NULL)
#1 /vagrant/www/fitster/app/Http/Controllers/Coach/ServicesController.php(135): App\Models\Service->createFrom(Object(App\Http\Requests\CoachServiceRequest))
#2 [internal function]: App\Http\Controllers\Coach\ServicesController->store(Object(App\Http\Requests\CoachServiceRequest), 'ru', 'llebedev818963')
#59 /vagrant/www/fitster/tests/Feature/ServiceFeatureTest.php(338): Illuminate\Support\Collection->each(Object(Closure))
#60 [internal function]: Tests\Http\ServiceFeatureTest->testCreateCoachServiceWithOffers()
```

Just need to replace Symfony Component Debug to "some" Laravel Debug system 😄

**Comment by sisve** [comment]
That would be problematic when Laravel calls an application callback/event, and we hide the Laravel caller information...

**Comment by uonick** [comment]
:weary:

**Comment by michaeldyrynda** [comment]
You could always check out [Collision](https://github.com/nunomaduro/collision). 

I think Taylor mentioned he was considering it for 5.6. Note, it requires PHP >= 7.1.

**Comment by uonick** [comment]
Good news! Thanks!
